local_backend:
  url: http://localhost:8082/api/v1
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "/src/assets"
public_folder: "assets"

locale: 'pl'
i18n:
  structure: single_file
  locales: [ pl ]
  default_locale: pl

collections:
  - name: 'pages'
    label: "Strony"
    i18n:
      structure: single_file
      locales: [ pl ]
    sortable_fields: [ ]
    editor:
      preview: false
    files:
      - name: "homepage"
        i18n: true
        label: "Strona główna"
        file: src/content/pageHomepage/pageHomepage.md
        fields:
          - label: "Zdjęcie"
            i18n: true
            name: "hero"
            widget: "object"
            summary: 'Ustawienia baneru'
            fields:
              - { label: "Zdjęcie w tle", name: "heroImage", widget: "image", choose_url: false, public_folder: '/src/assets/', i18n: duplicate }
#              - { label: "Zdjęcie w tle - dla tabletów (1024px)", name: "heroImageTablet", widget: "image", choose_url: false, public_folder: '/src/assets/', i18n: duplicate, hint: 'Mniejsze zdjęcie pomaga w szybkości ładowania strony' }
#              - { label: "Zdjęcie w tle - dla telefonów (768px)", name: "heroImageMobile", widget: "image", choose_url: false, public_folder: '/src/assets/', i18n: duplicate, hint: 'Mniejsze zdjęcie pomaga w szybkości ładowania strony'}

      - name: "about"
        label: "O mnie" # Used in the UI
        file: src/content/pageAbout/pageAbout.md
        i18n: true
        fields:
          - { label: "Tytuł strony", name: "title", widget: "string", i18n: true }
          - { label: "Opis", name: "description", widget: "markdown", i18n: true }
      - name: "portfolio"
        label: "Portfolio" # Used in the UI
        file: src/content/pagePortfolio/pagePortfolio.md
        i18n: true
        fields:
          - { label: "Tytuł strony", name: "title", widget: "string", i18n: true }
          - label: "Ilustracje"
            name: "items"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
              - {label: "Widoczna", name: "visible", widget: "boolean", default: true}
              - {label: "Tytuł", name: "title", widget: "string"}
              - {label: "Slug", name: "slug", widget: "string", hint: 'Jaka ma być końcóweczka adresu strony. Bez spacji i polskich znaków. np. /portfolio/na-kurze-roze'}
              - {label: "Grafika", name: "image", widget: "image", choose_url: false, public_folder: '/src/assets/', i18n: duplicate }
              - {label: "Opis", name: "description", widget: "markdown", i18n: true, required: false }
      - name: "offer-page"
        label: "Oferta" # Used in the UI
        i18n: true
        file: src/content/pageOffer/pageOffer.md
        fields:
          - { label: "Tytuł strony", name: "title", widget: "string", i18n: true }
          - { label: "Opis", name: "description", widget: "markdown", i18n: true,  required: false }
      - name: "contact-page"
        label: "Kontakt" # Used in the UI
        i18n: true
        file: src/content/pageContact/pageContact.md
        fields:
          - { label: "Tytuł strony", name: "title", widget: "string", i18n: true }
          - { label: "Opis", name: "description", widget: "markdown", i18n: true,  required: false }

  - name: 'settings'
    label: 'Ustawienia'
    sortable_fields: [ ]
    i18n:
      structure: single_file
      locales: [ pl ]
    files:
      - file: src/content/settings/settings.md
        label: 'Meta tagi'
        name: 'meta'
        i18n: true
        create: false
        delete: false
        editor:
          preview: false
        fields:
          - label: "Meta Tagi"
            hint: 'Meta tagi - https://pomoc.home.pl/baza-wiedzy/najwazniejsze-znaczniki-meta-i-ich-funkcje-meta-tagi'
            i18n: true
            name: "metaTags"
            widget: "object"
            fields:
              - { label: "Tytuł strony", name: "title", hint: 'Widoczny w tytule przeglądarki', widget: "string" , i18n: true }
              - { label: "Meta description - opis strony", name: "description", hint: 'Najlepiej między 50 a 150 znaków', widget: "text", i18n: true }
              - { label: "Meta keywords - Słowa kluczowe", name: "keywords", hint: 'Oddzielone przecinkami', widget: "text", i18n: true }
          - label: "Tagi Open Graph"
            hint: "Tagi Open Grap - Np. Jak ma wyglądać podgląd, kiedy wysyłasz stronę przez Facebooka https://lumo.pl/blog/open-graph/. Sprawdź jak wygląda podgląd na https://developers.facebook.com/tools/debug/"
            i18n: true
            name: "openGraph"
            widget: "object"
            summary: 'Tagi Open Graph'
            fields:
              - { label: "Tytuł - Podgląd w social mediach", name: "title", widget: "string", hint: 'Tytuł podglądu kiedy np. kiedy wysyłasz stronę przez Facebooka albo LinkedIn', i18n: true }
              - { label: "Opis - Podgląd w social mediach", name: "description", widget: "text", i18n: true }
              - label: "Zdjęcie - Podgląd w social mediach"
                name: "image"
                widget: "image"
                choose_url: false
                public_folder: "/src/assets/"
                i18n: "duplicate"
